a=int(input("Enter number n1:"))
b=int(input("Enter number n2:"))
print("add:",a+b)
print("sub:",a-b)
print("multiply:",a+b)
print("division:",a/b)
print("floor division",a//b)
print("module",a%b)
print("power",a**b)